deployment:
  tasks:
    - echo "Starting Deployment"
    - export DEPLOYPATH=/home/gigamasc/public_html/prueba
    - /bin/cp -R dist $DEPLOYPATH
    - cd $DEPLOYPATH
    - echo "Deployment Finished"
